.TH GOATATTACK 6 "March 2023" "goat attack" "Multiplayer shooter"
.SH NAME
goatattack \- multiplayer pixel art shooter game
.SH SYNOPSIS
.B goatattack [path/to/datafolder]
.SH DESCRIPTION
Goat Attack is a fast-paced multiplayer pixel art shooter game. Optionally, you can append a data folder.
.SH CONFIGURATION
The configuration is a simple key=value file. The configuration file is stored in your home directory under
.I ~/.goatattack
or
.I ~/.config/goatattack
and you should not edit this file directly unless you know what you do. You can change your settings in a running game session with
.I /get
and
.I /set
command. You have to be
.I /op
to be able to do this. Have a look into the goatattack-server manual page for further informations.
.SH MORE INFORMATIONS
Please read the README file for more informations.
.SH AUTHORS
Goat Attack and its manuals were written by Philippe Widmer <pw@earthwave.ch>, and are licensed under the terms of GPLv3 licenses.
