.PHONY: clean All

All:
	@echo "----------Building project:[ GoatAttack - Debug ]----------"
	@cd "GoatAttack" && $(MAKE) -f  "GoatAttack.mk"
clean:
	@echo "----------Cleaning project:[ GoatAttack - Debug ]----------"
	@cd "GoatAttack" && $(MAKE) -f  "GoatAttack.mk" clean
