.PHONY: clean All

All:
	@echo "----------Building project:[ MapEditor - Debug ]----------"
	@cd "MapEditor" && $(MAKE) -f  "MapEditor.mk"
clean:
	@echo "----------Cleaning project:[ MapEditor - Debug ]----------"
	@cd "MapEditor" && $(MAKE) -f  "MapEditor.mk" clean
