.TH GOATATTACK-MAPEDITOR 6 "September 2016" "goat attack" "Multiplayer shooter map editor"
.SH NAME
goatattack-mapeditor \- multiplayer pixel art shooter game map editor
.SH SYNOPSIS
.B goatattack-mapeditor
.SH DESCRIPTION
Goat Attack Map Editor is the map editor to the fast-paced multiplayer pixel art shooter game
Goad Attack.
.SH MORE INFORMATIONS
Please read the README file or visit \fIwww.goatattack.net\fR for more informations.
.SH AUTHORS
Goat Attack and its manuals were written by Philippe Widmer <pw@earthwave.ch>, and are licensed under the terms of GPLv3 licenses.
