.TH GOATATTACK-MASTERSERVER 6 "September 2016" "goat attack" "Multiplayer shooter master server"
.SH NAME
goatattack-masterserver \- multiplayer pixel art shooter game masterserver
.SH SYNOPSIS
.B goatattack-masterserver
.SH DESCRIPTION
The masterserver will listen on ports 25112 and 25113. The heartbeat UDP socket on port 25112
receives a heartbeart approx. all 5 seconds from dedicated servers. The masterserver knows about
all running game servers. A game client receives all running game server after connecting TCP
port 25113.
.SH MORE INFORMATIONS
Please read the README file or visit \fIwww.goatattack.net\fR for more informations.
.SH AUTHORS
Goat Attack and its manuals were written by Philippe Widmer <pw@earthwave.ch>, and are licensed under the terms of GPLv3 licenses.
